- README.md
Just made the change in the README since I needed to change something in order to make a PR :)
---
> __FYA:__ @Workiva/ui-platform-pp
> UIP-1357 Release over_react_test 1.0.0

- CHANGELOG.md
- pubspec.yaml
__Misc__
* #8: Update prop error message to make it more DDC friendly
---
> UIP-2331: Release over_react_test 1.0.1

- pubspec.yaml
* [UIP-1682: Test that testId is forwarded in commonComponentTests](https://github.com/Workiva/over_react_test/pull/15)
* [UIP-1112: Support passing in components in getByTestId](https://github.com/Workiva/over_react_test/pull/16)
Requested by: @jacehensley-wf
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/over_react_test/compare/1.1.1...version-bump-over_react_test-1-2-0
Diff Between Last Tag and New Tag: https://github.com/Workiva/over_react_test/compare/1.1.1...1.2.0
> UIP-2556 Release over_react_test 1.2.0

- docs.yml
docs only PR to allow this to show up on dev portal
@Workiva/ui-platform-pp @Workiva/web-platform-pp
> UIP-2674 add docs.yaml

- README.md
> Fix variable name in naming convention example

- pubspec.yaml
* [Fix variable name in naming convention example](https://github.com/Workiva/over_react_test/pull/26)
* [UIP-2888 Use dependency_validator](https://github.com/Workiva/over_react_test/pull/28)
* [Add CODEOWNERS file](https://github.com/Workiva/over_react_test/pull/29)
* [BUILDTOOLS-2329: Update Dockerfile to mirror smithy.yaml](https://github.com/Workiva/over_react_test/pull/31)
* [Use dependency validator](https://github.com/Workiva/over_react_test/pull/32)
* [Include ssh access in dockerfile](https://github.com/Workiva/over_react_test/pull/34)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/over_react_test/compare/1.3.1...Workiva:release_over_react_test_1_3_2
Diff Between Last Tag and New Tag: …
> UIP-2730 Release over_react_test 1.3.2

- pubspec.yaml
* [Fix Dart SDK 2 typing issues](https://github.com/Workiva/over_react_test/pull/39)
* [AF-321: Add generic triggerDocumentMouseEvent util for non click events](https://github.com/Workiva/over_react_test/pull/40)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/over_react_test/compare/1.3.2...Workiva:release_over_react_test_1_4_0
Diff Between Last Tag and New Tag: https://github.com/Workiva/over_react_test/compare/1.3.2...1.4.0
> Release over_react_test 1.4.0

- pubspec.yaml
* [af_new_drydock_image](https://github.com/Workiva/over_react_test/pull/43)
* [AF-1950 Fix typo in jacket.dart](https://github.com/Workiva/over_react_test/pull/45)
* [AF-2001 Add a TestJacket-only library](https://github.com/Workiva/over_react_test/pull/46)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/over_react_test/compare/1.4.0...Workiva:release_over_react_test_1_5_0
Diff Between Last Tag and New Tag: https://github.com/Workiva/over_react_test/compare/1.4.0...1.5.0
> AF-324 Release over_react_test 1.5.0

- pubspec.yaml
* [AF-3425 Add getAllByTestId](https://github.com/Workiva/over_react_test/pull/48)
Requested by: @aaron.lademann
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/over_react_test/compare/1.5.0...Workiva:release_over_react_test_1.6.0
Diff Between Last Tag and New Tag: https://github.com/Workiva/over_react_test/compare/1.5.0...1.6.0
> AF-2040 Release over_react_test 1.6.0

- pubspec.yaml
* [CP-4147: Widen over_react range](https://github.com/Workiva/over_react_test/pull/58)
Requested by: @evan.weible
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/over_react_test/compare/2.2.0...Workiva:release_over_react_test_2.3.0
Diff Between Last Tag and New Tag: https://github.com/Workiva/over_react_test/compare/2.2.0...2.3.0
> CPLAT-3914 Release over_react_test 2.3.0

- pubspec.yaml
* [CPLAT-4151 Run CI on dart1 and dart2](https://github.com/Workiva/over_react_test/pull/60)
* [CPLAT-4301 : Make compatible with react.dart 5.0.0-wip](https://github.com/Workiva/over_react_test/pull/62)
Requested by: @aaron.lademann
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/over_react_test/compare/2.3.0...Workiva:release_over_react_test_2.4.0
Diff Between Last Tag and New Tag: https://github.com/Workiva/over_react_test/compare/2.3.0...2.4.0
> CPLAT-4153 Release over_react_test 2.4.0

- pubspec.yaml
* [Work around a bug in DDC where SvgElement className isn't String](https://github.com/Workiva/over_react_test/pull/64)
Requested by: @seanburke-wf
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/over_react_test/compare/2.4.0...Workiva:release_over_react_test_2.4.1
Diff Between Last Tag and New Tag: https://github.com/Workiva/over_react_test/compare/2.4.0...2.4.1
> CPLAT-4774 Release over_react_test 2.4.1

- .travis.yml
- Dockerfile
- lib/src/over_react_test/js_component.dart
- lib/src/over_react_test/react_util.dart
- pubspec.yaml
We are updating over_react_test repo with react 16. We updated the JS Interop Helpers, so we must apply those updates to over_react_test.
jsify references have been changed to jsifyAndAllowInterop
importing dart:util
Update jsify to jsifyAndAllowInterop
> CPLAT-5477 - Update references to old JS Interop Helpers

- pubspec.yaml
* [CPLAT-3300: CP Code Review and PR Merging Team agreement update](https://github.com/Workiva/over_react_test/pull/66)
* [CPLAT-5477 - Update references to old JS Interop Helpers](https://github.com/Workiva/over_react_test/pull/68)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/over_react_test/compare/2.4.1...Workiva:release_over_react_test_2.5.0
Diff Between Last Tag and New Tag: https://github.com/Workiva/over_react_test/compare/2.4.1...2.5.0
> CPLAT-4928 Release over_react_test 2.5.0

- pubspec.yaml
* [CPLAT-5648 Accommodate findAllInRenderedTree being passed text nodes in React 16](https://github.com/Workiva/over_react_test/pull/71)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/over_react_test/compare/2.5.0...Workiva:release_over_react_test_2.5.1
Diff Between Last Tag and New Tag: https://github.com/Workiva/over_react_test/compare/2.5.0...2.5.1
> CPLAT-5609 Release over_react_test 2.5.1

- README.md
The current API documentation link does not work.  Updated to a working link.
> API documentation link was broken

- lib/src/over_react_test/common_component_util.dart
Because `component2`'s `propTypes` do not stop a component from rendering, tests checking for `propTypes` needed to have the ability to continue running the tests even if the `render()` (in the form of mounting) throws.
- Add a try / catch
- Only check log messages if there is one expected.
@greglittlefield-wf @kealjones-wk @aaronlademann-wf @sydneyjodon-wk  …
> CPLAT-7663 Add Mount Error Awareness

- Dockerfile
- pubspec.yaml
We can finally start removing Dart1 and this PR is the first step. Updating Dockerfile will allow us to start removing dart1 in other repos without worrying that consumer PR might fail.
- Remove `dart1` stage from `Dockerfile`
- Update dependencies
> CPLAT-8021: Dart 1 removal - Phase 1

- pubspec.yaml
* [CPLAT-8021: Dart 1 removal - Phase 1](https://github.com/Workiva/over_react_test/pull/83)
* [React 16 Component2 Updates](https://github.com/Workiva/over_react_test/pull/86)
Requested by: @joebingham-wk
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/over_react_test/compare/2.5.2...Workiva:release_over_react_test_2.6.0
Diff Between Last Tag and New Tag: https://github.com/Workiva/over_react_test/compare/2.5.2...2.6.0
> RM-58742 Release over_react_test 2.6.0

- .travis.yml
- Dockerfile
- analysis_options.yaml
- lib/src/over_react_test/common_component_util.dart
- lib/src/over_react_test/custom_matchers.dart
- lib/src/over_react_test/dom_util.dart
- lib/src/over_react_test/jacket.dart
- lib/src/over_react_test/js_component.dart
- lib/src/over_react_test/react_util.dart
- lib/src/over_react_test/zone_util.dart
- pubspec.yaml
- test/over_react_test/common_component_util_test.dart
- test/over_react_test/custom_matchers_test.dart
- test/over_react_test/jacket_test.dart
- test/over_react_test/react_util_test.dart
- tool/dev.dart
Clean up the lints related to Dart2 syntax updates.
- Clean up any code causing a lint
@kealjones-wk @greglittlefield-wf @aaronlademann-wf @sydneyjodon-wk 
> Clean Up Lints

- README.md
@corwinsheahan-wf please merge this
> Remove Dart 1 only instructions

- pubspec.yaml
* [CPLAT-6704 Create PropType Testing Utils](https://github.com/Workiva/over_react_test/pull/84)
* [Clean Up Lints](https://github.com/Workiva/over_react_test/pull/88)
* [Remove Dart 1 only instructions](https://github.com/Workiva/over_react_test/pull/90)
Requested by: @joebingham-wk
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/over_react_test/compare/2.6.0...Workiva:release_over_react_test_2.7.0
Diff Between Last Tag and New Tag: https://github.com/Workiva/over_react_test/compare/2.6.0...2.7.0
> RM-61439 Release over_react_test 2.7.0

- pubspec.yaml
* [Add Component Version Auto Detection](https://github.com/Workiva/over_react_test/pull/89)
* [CPLAT-10387 CPLAT-3700 Re-instate prop forwarding tests for new boilerplate](https://github.com/Workiva/over_react_test/pull/95)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/over_react_test/compare/2.8.0...Workiva:release_over_react_test_2.9.0
Diff Between Last Tag and New Tag: https://github.com/Workiva/over_react_test/compare/2.8.0...2.9.0
> RM-63819 Release over_react_test 2.9.0

- CHANGELOG.md
- pubspec.yaml
> RM-83504 Release over_react_test 2.10.1

- pubspec.yaml
* [Widen OverReact constraint in preparation for v4.0.0](https://github.com/Workiva/over_react_test/pull/108)
Requested by: @joebingham-wk
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/over_react_test/compare/2.10.1...Workiva:release_over_react_test_2.10.2
Diff Between Last Tag and New Tag: https://github.com/Workiva/over_react_test/compare/2.10.1...2.10.2
> RM-83506 Release over_react_test 2.10.2

- CHANGELOG.md
When releasing 2.10.2, I forgot to add the changelog entry. This adds it for that version so that for the next release, everything will be caught up.
- Add a changelog entry for https://github.com/Workiva/over_react_test/pull/108
@aaronlademann-wf @sydneyjodon-wk @greglittlefield-wf 
> Add changelog entry for 2.10.2

- pubspec.yaml
* [DE-659: Delete docs.yml file created for Dev Portal.](https://github.com/Workiva/over_react_test/pull/118)
* [Upgrade dependency_validator](https://github.com/Workiva/over_react_test/pull/126)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/over_react_test/compare/2.11.2...Workiva:release_over_react_test_2.11.3
Diff Between Last Tag and New Tag: https://github.com/Workiva/over_react_test/compare/2.11.2...2.11.3
This pull request can be recreated by clicking [here](https://w-rmconsole.appspot.com/api/v2/rosie/reTriggerReleaseEvents/487168386 …
> RM-116083 Release over_react_test 2.11.3

- pubspec.yaml
* [Raise Max Versions](https://github.com/Workiva/over_react_test/pull/130)
* [Fix wildcard to include branch names with slashes](https://github.com/Workiva/over_react_test/pull/131)
* [Raise More Max Versions](https://github.com/Workiva/over_react_test/pull/134)
* [Narrow dependency_validator range to avoid NNBD issue](https://github.com/Workiva/over_react_test/pull/136)
* [Update references to the previous team name](https://github.com/Workiva/over_react_test/pull/137)
* [Add basic skynet.yaml](https://github.com/Workiva/over_react_test/pull/138)
Requested by: @robbecker-wf
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/over_react_test/compare/2.11.3...Workiva:release_over_react_test_2.11.4
Diff Between Last Tag …
> RM-120925 Release over_react_test 2.11.4

- pubspec.yaml
* [Avoid meta 1.10.0](https://github.com/Workiva/over_react_test/pull/143)
* [Add workiva_dependency_constrainer](https://github.com/Workiva/over_react_test/pull/144)
* [Rollout Analyzer 5](https://github.com/Workiva/over_react_test/pull/146)
* [Dart 2.19](https://github.com/Workiva/over_react_test/pull/148)
* [FED-1852 Remove usages of deprecated APIs to be removed in react-dart 7.0.0](https://github.com/Workiva/over_react_test/pull/149)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/over_react_test/compare/2.11.5...Workiva:release_over_react_test_2.11.6
Diff Between Last Tag and New Tag: https://github.com/Workiva/over_react_test/compare/2.11.5...2.11.6
The logs for the request …
> RM-179718 Release over_react_test 2.11.6

- pubspec.yaml
* [Allow react 7 and w_flux 3](https://github.com/Workiva/over_react_test/pull/152)
Requested by: @robbecker-wf
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/over_react_test/compare/2.11.6...Workiva:release_over_react_test_2.11.7
Diff Between Last Tag and New Tag: https://github.com/Workiva/over_react_test/compare/2.11.6...2.11.7
This pull request can be recreated by clicking [here](https://w-rmconsole.appspot.com/api/v2/rosie/reTriggerReleaseEvents/4871683861643264/?repo_name=Workiva%2Fover_react_test&pull_number=153)
> RM-222445 Release over_react_test 2.11.7

- pubspec.yaml
> Point to released null-safe over_react

- pubspec.yaml
* [react 7 and w_flux 3 step 2](https://github.com/Workiva/over_react_test/pull/154)
* [FED-2442 Merge version 3.0.0 changes to master](https://github.com/Workiva/over_react_test/pull/160)
* [Point to released null-safe over_react](https://github.com/Workiva/over_react_test/pull/162)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/over_react_test/compare/2.11.7...Workiva:release_over_react_test_3.0.0
Diff Between Last Tag and New Tag: https://github.com/Workiva/over_react_test/compare/2.11.7...3.0.0
This pull request can be recreated by …
> RM-223682 Release over_react_test 3.0.0

- pubspec.yaml
* [FEDX-691 : GHA OSS changes](https://github.com/Workiva/over_react_test/pull/164)
* [raise_min_dart_sdk_2_19](https://github.com/Workiva/over_react_test/pull/168)
Requested by: @robbecker-wf
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/over_react_test/compare/3.0.0...Workiva:release_over_react_test_3.0.1
Diff Between Last Tag and New Tag: https://github.com/Workiva/over_react_test/compare/3.0.0...3.0.1
This pull request can be recreated by clicking [here](https://w-rmconsole.appspot.com/api/v2/rosie/reTriggerReleaseEvents/4871683861643264/?repo_name=Workiva%2Fover_react …
> RM-250121 Release over_react_test 3.0.1
