Workiva/over_react_test

.travis.yml, pubspec.yaml, smithy.yaml
We want to make sure the tests can be run with the DDC
- Bump dep version constraints
- Verify tests pass by:
- Run `pub serve test --web-compiler=dartdevc` in one terminal
- And `pub run test -p chrome --pub-serve=8080 test/over_react_test.dart` in another terminal
N/A
---
=> UIP-2429: Get tests passing with the DDC

lib/src/over_react_test/custom_matchers.dart, pubspec.yaml
> Related to: https://github.com/Workiva/over_react/pull/92
When running tests in the DDC the `Error.safeToString` was kinda a PITA
- Do not use `Error.safeToString`
Verify tests still pass
N/A
---
=> UIP-2464 Update prop error matcher

.travis.yml, pubspec.yaml
* [UIP-2512 Add more utils from over_react](https://github.com/Workiva/over_react_test/pull/11)
Requested by: @jacehensley-wf
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/over_react_test/compare/1.0.1...version-bump-over_react_test-1-1-0_4
Diff Between Last Tag and New Tag: https://github.com/Workiva/over_react_test/compare/1.0.1...1.1.0
=> UIP-2465 Release over_react_test 1.1.0

lib/src/over_react_test/react_util.dart, test/over_react_test/react_util_test.dart
Our `getByTestId` helper function didn't support taking in `react.Component`s. It's an easy one line quality of life improvement, we should just support it.
- If the passed root is a `react.Component` then use `root.jsThis` as the root.
- Since all our other `get{{___}}ByTestId` functions use `getByTestId` under the hood they do not need to be updated.
- Added a test
- Verify tests pass
N/A
---
=> UIP-1112: Support passing in components in getByTestId

lib/src/over_react_test/common_component_util.dart, test/over_react_test/common_component_util_test.dart, test/over_react_test/utils/test_common_component_required_props.dart
We are rendering the component outside of a test block, this is a problem if a consumer needs to use a setUp (setting up mocks). We should move everything within test blocks.
Known functions that need to be updated:
- testRequiredProps
- testClassNameOverrides
Wrapped the offending methods in test blocks so they would run the `factory` related code at the right time.
- Run tests
- Verify against `SingleEdgeFormItemComponent` tests in [graph_ui branch](https://github.com/Workiva/graph_ui/compare/master...johnbland-wf:SOX-5764-single-edge-form-item?expand=1)
Consumers using `commonComponentTests`
---
=> UIP-2621: Do not do anything outside of test blocks in commonComponentTests

pubspec.yaml
* [UIP-2621: Do not do anything outside of test blocks in commonComponentTests](https://github.com/Workiva/over_react_test/pull/18)
Requested by: @leviwith-wf
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/over_react_test/compare/1.2.0...version-bump-over_react_test-1-2-1
Diff Between Last Tag and New Tag: https://github.com/Workiva/over_react_test/compare/1.2.0...1.2.1
=> UIP-2630 Release over_react_test 1.2.1

pubspec.yaml
Widen react-dart dependency to include 4.0.0.
react-dart 4.0.0 includes improvements to Dart component instance management that help avoid certain memory leaks. See more info here: https://github.com/cleandart/react-dart/pull/127.
While this release contains breaking changes, those breakages are limited to internals that should be smoothed over by over_react, and should not affect the majority of consumers.
Widen react-dart version range to include 4.0.0.
Once this range has been widened throughout the Workiva's dependency tree, everyone should get 4.0.0 for free.
- (This PR will likely not result in any changes to resolved dependencies)
1. Add the following to your pubspec.yaml:
```yaml
dependency_overrides:
react: ^4.0.0
over_react:
git:
url: git@github.com:Workiva/over_react.git
ref: …
```
=> UIP-2681 Widen react-dart range to pull in memory leak fixes

pubspec.yaml
* [UIP-2674 add docs.yaml](https://github.com/Workiva/over_react_test/pull/20)
* [UIP-2681 Widen react-dart range to pull in memory leak fixes](https://github.com/Workiva/over_react_test/pull/21)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/over_react_test/compare/1.2.1...Workiva:release_over_react_test_1_2_2
Diff Between Last Tag and New Tag: https://github.com/Workiva/over_react_test/compare/1.2.1...1.2.2
=> UIP-2638 Release over_react_test 1.2.2

lib/src/over_react_test/dom_util.dart, test/over_react_test/custom_matchers_test.dart
- `triggerTransitionEnd` no longer works as expected in Chrome 61 due to https://github.com/dart-lang/sdk/issues/26972.
- When `triggerFocus` and `triggerTransitionEnd` fail, they cause tests to hang until they time out
- Fix `triggerTransitionEnd` in Chrome 61
- Add reasonable timeouts to `triggerFocus` and `triggerTransitionEnd` so that they don't cause tests to hang for as long
- Verify CI passes
- Verify all unit tests pass in Chrome 61 (you may need to keep the browser window focused)
`triggerFocus` and `triggerTransitionEnd` 
---
=> UIP-2718 Make triggerTransitionEnd work for Chrome 61

pubspec.yaml
* [UIP-2718 Make triggerTransitionEnd work for Chrome 61](https://github.com/Workiva/over_react_test/pull/23)
Requested by: @clairesarsam-wf
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/over_react_test/compare/1.2.2...Workiva:release_over_react_test_1_3_0
Diff Between Last Tag and New Tag: https://github.com/Workiva/over_react_test/compare/1.2.2...1.3.0
=> UIP-2686 Release over_react_test 1.3.0

lib/src/over_react_test/dom_util.dart, pubspec.yaml
`triggerTransitionEnd` was timing out in content-shell.
Use the `Element.transitionEndEvent.getEventType(...)` API to ensure the name of event we're dispatching is the same name used by the `onTransitionEnd` stream. 
Lucky this API exists; now we don't have to guess!
* Verify all tests pass locally in content-shell.
* Verify that all parts of WSD build (Smithy, coverage, JS unit tests pass)
* Test branch: https://github.com/greglittlefield-wf/web_skin_dart/branches/all?utf8=%E2%9C%93&query=transitionend_fix_test
`triggerTransitionEnd`
---
=> UIP-2727 Release over_react_test 1.3.1

.travis.yml, pubspec.yaml, smithy.yaml
Now that `dependency_validator` is published we should use it.
- Add `dependency_validator` as a dev dep and runs its check during CI.
- Verify CI still passes
N/A
---
FYA: @Workiva/ui-platform-pp @Workiva/web-platform-pp
=> UIP-2888 Use dependency_validator

Dockerfile
During consumer testing it was noticed that the Dockerfile didn't have the necessary credentials to pull from a non-pub location (i.e. git).
Include ssh-agent in `Dockerfile`
Verify build passes. (view the last commit found here, https://github.com/Workiva/over_react_test/pull/33 and ensure that the `pub get` resolves
n/a
---
=> Include ssh access in dockerfile

lib/src/over_react_test/dom_util.dart, test/over_react_test/dom_util_test.dart
The logic previously contained in `triggerDocumentClick` is actually useful for all kinds of different mouse events.
Move logic to a new method, `triggerDocumentMouseEvent`, which can be used to trigger any type of mouseevent.
Tests should pass.
None.
---
=> AF-321: Add generic triggerDocumentMouseEvent util for non click events

.travis.yml, Dockerfile, tool/dev.dart
The following pull request has been created by App Frameworks to help move consumers to the latest Smithy image. This was done because of an issue with Dartium and Content-Shell that would fail your CIs. Please seethis [Wiki Question](https://wiki.atl.workiva.net/cq/viewquestion.action?id=96308901&answerId=96308907)for additional context.
The following changes have been made:
* All instances of the production Smithy image have been updated to `drydock-prod.workiva.net/workiva/smithy-runner-generator:355624`.
If you have any questions, please reach out to us in the Support:H5 / Dart Hipchat room
=> af_new_drydock_image

lib/src/over_react_test/jacket.dart
- There was a typo in jacket.dart
- Fixed the typo
- CI should still be happy
- None
---
=> AF-1950 Fix typo in jacket.dart

Dockerfile, lib/jacket.dart, lib/src/over_react_test/jacket.dart, pubspec.yaml
The only library currently exposed by `over_react_test` includes the `TestJacket`, but also all of the react test utilities.  Some of the test utilities utilize `mirrors` - which are known to bloat the size of dart2js compiled output.  This is less than ideal for consumers who do not need to make use of any test utilities.
Add a `lib/jacket.dart` entrypoint that only exposes the `TestJacket`.
Updated some stale dependency lower bounds.
CI passes
None expected - new entrypoint only.
---
> __FYA:__ @kealjones-wk @clairesarsam-wf @greglittlefield-wf
=> AF-2001 Add a TestJacket-only library

lib/src/over_react_test/react_util.dart, test/over_react_test/react_util_test.dart
Consumers wanted a function like `getByTestId` that look up React components by their test IDs, but returns all results instead of at most one.
- Add `getAllByTestId`/`getAllComponentsByTestId`
- Add tests (copypasta'd and adapted from `getByTestId` tests)
Boyscouting:
- Update some bad test descriptions
- Update doc comment for `getByTestId`
- Verify CI passes
- Verify this works for the consumer use-case
- `getByTestId`
=> AF-3425 Add getAllByTestId

lib/src/over_react_test/common_component_util.dart, lib/src/over_react_test/custom_matchers.dart, lib/src/over_react_test/wrapper_component.dart, test/over_react_test/common_component_util_test.dart, test/over_react_test/jacket_test.dart, test/over_react_test/react_util_test.dart, test/over_react_test/utils/nested_component.dart, test/over_react_test/utils/test_common_component.dart, test/over_react_test/utils/test_common_component_nested.dart, test/over_react_test/utils/test_common_component_nested2.dart, test/over_react_test/utils/test_common_component_required_props.dart
Need updated boilerplate for Dart 1/2 compatibility.
* Run the over_react_codemod script and update components with new boilerplate
* Fix class declaration using some mixins which were not picked up by codemod
* CI Passes
None
---
> __FYA:__ @greglittlefield-wf @aaronlademann-wf @joelleibow-wf @evanweible-wf @sebastianmalysa-wf @robbecker-wf
=> AF-3525: Update component boilerplate for Dart 1/2

.travis.yml, Dockerfile, lib/src/over_react_test/common_component_util.dart, lib/src/over_react_test/react_util.dart, pubspec.yaml, test/over_react_test/validation_util_test.dart
Need dart 2 compatibility
* Dependency updates
* Typing updates
* Comment out the function `getComponentPropKeys`. This method uses mirrors, which are not compatible with web development on Dart 2. [AF-3700](https://jira.atl.workiva.net/browse/AF-3700) will re-add this functionality back in w/out using mirrors once we're fully transitioned to Dart 2
* CI Passes (currently only running Dart 1)
* Pull this branch locally and publink the builder_generate_public_class branch of over_react to allow pub get to resolve on Dart 2. Then, verify that all tests pass on Dart 2.
---
> __FYA:__ @greglittlefield-wf @aaronlademann-wf @joelleibow-wf @evanweible-wf @sebastianmalysa-wf @robbecker-wf
=> AF-3567: Dart 2 compatibility (almost!)

lib/src/over_react_test/wrapper_component.dart, pubspec.yaml, test/over_react_test/jacket_test.dart, test/over_react_test/react_util_test.dart, test/over_react_test/utils/nested_component.dart, test/over_react_test/utils/test_common_component.dart, test/over_react_test/utils/test_common_component_nested.dart, test/over_react_test/utils/test_common_component_nested2.dart, test/over_react_test/utils/test_common_component_required_props.dart
Dart 1-2 transition boilerplate updated to make the initializers for factories and meta constants private. This repo needed to be updated.
Re-run codemod script
CI Passes
None
---
> __FYA:__ @evanweible-wf @sebastianmalysa-wf @smaifullerton-wk @georgelesica-wf
=> AF-3857: run latest codemod

lib/src/over_react_test/wrapper_component.dart, test/over_react_test/jacket_test.dart, test/over_react_test/react_util_test.dart, test/over_react_test/utils/nested_component.dart, test/over_react_test/utils/test_common_component.dart, test/over_react_test/utils/test_common_component_nested.dart, test/over_react_test/utils/test_common_component_nested2.dart, test/over_react_test/utils/test_common_component_required_props.dart
Need to make `$metaFor` initializers private
Make them private
CI Passes
None
---
> __FYA:__ @evanweible-wf @sebastianmalysa-wf @georgelesica-wf
=> AF-3891: make metaFor initializers private

pubspec.yaml
* [AF-3891: make metaFor initializers private](https://github.com/Workiva/over_react_test/pull/56)
Requested by: @corwin.sheahan
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/over_react_test/compare/2.1.0...Workiva:release_over_react_test_2.2.0
Diff Between Last Tag and New Tag: https://github.com/Workiva/over_react_test/compare/2.1.0...2.2.0
=> AF-3890 Release over_react_test 2.2.0

.travis.yml, pubspec.yaml
over_react 2.x release is imminent, need to widen range to include 2.x
Widen range
* CI Passes
N/A
---
> __FYA:__ @greglittlefield-wf @aaronlademann-wf @maxwellpeterson-wf @evanweible-wf @sebastianmalysa-wf @smaifullerton-wk @georgelesica-wf
=> CP-4147: Widen over_react range

lib/src/over_react_test/jacket.dart, lib/src/over_react_test/react_util.dart, pubspec.yaml, test/over_react_test/jacket_test.dart, test/over_react_test/react_util_test.dart
We need support for react-dart 5.0.0 (React 16) which no longer supports `isMounted`. 
- Add an `isMounted` method to TestJacket that is based upon a private variable that determines if the mount/unmount methods have been called.
- Add an `autoTearDownCallback` named argument to `render` and `renderAttachedToDocument` that allows the TestJacket to keep track of the `isMounted` status.  
probably.
---
> __FYA:__ @greglittlefield-wf @aaronlademann-wf
=> CPLAT-4301 : Make compatible with react.dart 5.0.0-wip

lib/src/over_react_test/custom_matchers.dart, test/over_react_test/custom_matchers_test.dart
As described at https://github.com/dart-lang/sdk/issues/36200, `SvgElement`'s `className` property returns `AnimatedString` in DDC. This makes classname matchers unusable with `SvgElement` due to runtime type errors.
Work around the issue by explicitly taking `AnimatedString` and getting a usable `String` value out of it.
Test added. CI passes.
Use of classname matchers.
---
=> Work around a bug in DDC where SvgElement className isn't String

lib/src/over_react_test/react_util.dart, test/over_react_test/react_util_test.dart
In React 16, the callback provided `react_test_utils.findAllInRenderedtree` gets called with DOM text nodes, whereas previously it was only called with DOM elements and React components.
Some utilities in over_react_test did not account for that, and threw as a result.
- Update conditionals in `getAllByTestId` and `findDescendantsWithProp` to not assume that the callback argument is only ever either a DOM element or React component.
- Add regression tests
Update `getAllByTestId`/`findDescendantsWithProp` implementations to work in React 16.
Please review: @aaronlademann-wf @kealjones-wk @joebingham-wk @tainhenning-wk 
While we perform many automated checks before …
=> CPLAT-5648 Accommodate findAllInRenderedTree being passed text nodes in React 16

Dockerfile, lib/src/over_react_test/common_component_util.dart, pubspec.yaml, test/over_react_test/common_component_util_test.dart, test/over_react_test/utils/test_common_component_required_props_commponent2.dart
Because `Component2` handles prop validation differently than `Component`, tests relating to prop validation need to be aware of `Component2` in order to test correctly.
- Add a new bool parameter checking for `Component2`
- Add a conditional that changes how props are validated based on the new parameter
- Update dockerfile
@greglittlefield-wf @kealjones-wk @aaronlademann-wf @sydneyjodon-wk  …
=> CPLAT-7370 Add Awareness for Component2

lib/src/over_react_test/react_util.dart, pubspec.yaml
This release adds support for react 5.x and over_react 3.x lines-of-release.
> Full support for react 5.1.0 / over_react 3.1.0 (`Component2`) will be added soon - is currently in the react-16-wip branch.
=> CPLAT-5662 Release over_react_test 2.5.2 (Includes CPLAT-7562)

lib/src/over_react_test/common_component_util.dart, test/over_react_test/common_component_util_test.dart, test/over_react_test/utils/test_common_component_required_props.dart, test/over_react_test/utils/test_common_component_required_props_commponent2.dart
Over_react_test's commonComponentTests with shouldTestRequiredProps as true are giving false positives.
The common_component_util.dart file has faulty logic that would never add any propDescriptors too nullableProps leading to the nullable props group/test (that is a foreach loop) to pass because it doesnt iterate over anything.
In addition to the faulty logic the components used to test the test suite dont have props with isNullable so even if the logic was correct our tests still wouldnt have caught it.
- fix logic for nullable props
- update test components to include a nullableRequiredProp
- add tests for UiComponent2 to nullable props test
Please review: …
=> CPLAT-7663 CPLAT-7763: commonComponentTests -> testRequiredProps tests are giving false positives

lib/src/over_react_test/jacket.dart, lib/src/over_react_test/react_util.dart, pubspec.yaml, test/over_react_test/helper_components/sample_function_component.dart, test/over_react_test/jacket_test.dart, test/over_react_test/react_util_test.dart
This patch includes improved error messages that are sent to the user when they attempt to test function components in an unsupported way.
---
@kealjones-wk @joebingham-wk @greglittlefield-wf
=> RM-62263 Release over_react_test 2.7.1

lib/src/over_react_test/jacket.dart, lib/src/over_react_test/react_util.dart, lib/src/over_react_test/zone_util.dart, pubspec.yaml, test/over_react_test.dart, test/over_react_test/console_log_utils_test.dart, test/over_react_test/helper_components/sample_component.dart, test/over_react_test/zone_render_tests.dart
Our current render utilities mount the component using a different zone then that of the test. We want to make them the same zone.
- Update `mount`, `render`, and `renderAttachedToDocument` to use set `currentComponentZone` to `Zone.current`.
- Add tests
- Update `mount`, `render`, and `renderAttachedToDocument` to run in the same zone as the test.
@aaronlademann-wf @greglittlefield-wf @kealjones-wk @sydneyjodon-wk 
- None! 🎉  …
=> CPLAT-8702 Update test utilities to use the current zone

CHANGELOG.md, pubspec.yaml
* [CPLAT-8702 Update test utilities to use the current zone](https://github.com/Workiva/over_react_test/pull/92)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/over_react_test/compare/2.7.1...Workiva:release_over_react_test_2.8.0
Diff Between Last Tag and New Tag: https://github.com/Workiva/over_react_test/compare/2.7.1...2.8.0
=> RM-63477 Release over_react_test 2.8.0

lib/src/over_react_test/common_component_util.dart, test/over_react_test/common_component_util_test.dart
Currently the common component tests require the flag `isComponent2` to be set to true in order to run tests specific to `Component2`. This can be automated, eliminating the need for the flag to be set.
- Add a check to the `ReactElement` type to determine if the version is one or two.
- Add automated `ReactElement` type check to `commonComponentTests`.
@aaronlademann-wf @greglittlefield-wf @kealjones-wk  …
=> Add Component Version Auto Detection

Dockerfile, lib/src/over_react_test/common_component_util.dart, lib/src/over_react_test/props_meta.dart, pubspec.yaml, test/over_react_test/common_component_util_test.dart, test/over_react_test/utils/test_common_component_new_boilerplate.dart
The new mixin-based boilerplate doesn't support access of prop keys outside of component classes, so we needed to update the `commonComponent` args `unconsumedPropKeys` and `skippedPropKeys`, which currently on accessing static meta variables, to work for new boilerplate components.
Only after updating that did I realize that those args were only used by the commented out unconsumed props test code, which was disabled since there was no path forward after `dart:mirrors` support was dropped.
However, the new boilerplate provides a path forward, since __all__ props classes mixed into a component are available via `propsMeta`! This allows us to reinstate unconsumed props tests for components that use the new mixin-based boilerplate.
- Re-instate commonComponentTests for components that use …
=> CPLAT-10387 CPLAT-3700 Re-instate prop forwarding tests for new boilerplate

lib/src/over_react_test/common_component_util.dart, lib/src/over_react_test/props_meta.dart, pubspec.yaml
Trying to render a component via `getPropsMeta` directly inside of `commonComponentTests` causes issues when the provided `factory` has required props that come from `setUp`-initialized variables.
For example:
```dart
setUp(() {
store = MyStore();
});
commonComponentTests(() => factory()..store = store);
```
This is because it's run before the consumer's `setUp` block.
Move `getPropsMeta` call to inside `test` block to ensure consumer `setUp` is called first
----
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/over_react_test/compare/2.9.0...Workiva:release_over_react_test_2.9.1
Diff Between Last Tag and New Tag: https://github.com/Workiva/over_react_test/compare/2.9.0...2.9.1
The logs for the request that created this PR can be …
=> RM-72266 Release over_react_test 2.9.1 (HOTFIX)

lib/src/over_react_test/common_component_util.dart, pubspec.yaml, test/over_react_test/common_component_util_test.dart, test/over_react_test/utils/test_common_component_required_props.dart, test/over_react_test/utils/test_common_component_required_props_commponent2.dart
Similar to https://github.com/Workiva/over_react_test/pull/97, Trying to render a component within an "isComponent2" check directly inside of `commonComponentTests` causes issues when the provided `factory` has accesses `setUp`-initialized variables.
For example:
```dart
setUp(() {
store = MyStore();
});
commonComponentTests(() => factory()..store = store.something);
```
This is because it's run before the consumer's `setUp` block.
- Move checks to inside `test` block to ensure consumer `setUp` is called first
- Add regression tests
---
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/over_react_test/compare/2.9.1...Workiva:release_over_react_test_2.9.2
Diff Between Last Tag and New Tag: …
=> RM-72281 Release over_react_test 2.9.2

lib/src/over_react_test/custom_matchers.dart, pubspec.yaml, test/over_react_test/custom_matchers_test.dart, test/over_react_test/helper_components/sample_component.dart
The `logsPropError` matcher that replaces the `throwsPropError` matcher had a typo in the message it expects from the logger.  It is missing a period.
1. Add the missing period.
2. Update the tests so that the first and second argument are used - which is the only way the missing period would have caused a test failure.
Fix logsPropError matcher message expectation
Please review: @greglittlefield-wf @joebingham-wk @corwinsheahan-wf  …
=> RM-72368 Release over_react_test 2.9.3 (Hotfix to fix prop type expectations)

lib/src/over_react_test/custom_matchers.dart, lib/src/over_react_test/react_util.dart, pubspec.yaml, test/over_react_test/react_util_test.dart
This hotfix addresses two issues recently released from this library:
1. https://github.com/Workiva/over_react_test/pull/100/commits/4080a46f2434089025320cabbd562ebffd1c3c1d The `throwsPropError*` matchers were [previously deprecated](https://github.com/Workiva/over_react_test/pull/84) / replaced by the new `logsPropError*` matchers.  However, the new matchers are only suitable for testing `PropError`s that happen within `UiComponent2.propTypes`.  `PropError`s can still be thrown elsewhere in components to produce full-blown RTEs - so the old matchers are still useful for testing that.
2. https://github.com/Workiva/over_react_test/pull/100/commits/9230eb8cc0637694802b13ddbbe1b131995b83e6 The `render()` utility function had different behavior between `UiComponent` and `UiComponent2` …
=> RM-73320 Release over_react_test 2.9.4 (render util hotfix)

CHANGELOG.md, lib/src/over_react_test/common_component_util.dart, pubspec.yaml
The new prop forwarding test utilities make use of `Object.values`, but MSIE 11 doesn't support it. This causes consumer test failures of the form:
```
NoSuchMethodError: Object doesn't support property or method 'values' (Error 438)
<some_test_file>.dart.js <line>:<col>   L.JsBackedMap.prototype.get$values
<some_test_file>.dart.js <line>:<col>    J.get$values$x
<some_test_file>.dart.js <line>:<col>   P.MapView.prototype.get$values
<some_test_file>.dart.js <line>:<col>  E.getForwardingTargets
<some_test_file>.dart.js <line>:<col>   E._testPropForwarding_closure.prototype.call$0
```
Shim the functionality so that consumer tests can run in MSIE 11.
Shim `Object.values` for MSIE 11
=> RM-73871 Release over_react_test 2.9.5 (MSIE 11 Object.values HOTFIX)

analysis_options.yaml, lib/src/over_react_test/wrapper_component.dart, pubspec.yaml, test/over_react_test/helper_components/sample_component.dart, test/over_react_test/helper_components/sample_component2.dart, test/over_react_test/jacket_test.dart, test/over_react_test/react_util_test.dart, test/over_react_test/utils/nested_component.dart, test/over_react_test/utils/test_common_component.dart, test/over_react_test/utils/test_common_component_nested.dart, test/over_react_test/utils/test_common_component_nested2.dart, test/over_react_test/utils/test_common_component_new_boilerplate.dart, test/over_react_test/utils/test_common_component_required_props.dart, test/over_react_test/utils/test_common_component_required_props_commponent2.dart
> __These changes / builds will first be reviewed by a member of the Client Platform team.__
>
> Repo owners will be notified when it is ready for additional review, merge and release.
While converting the boilerplate for OverReact component declaration from Dart 1 transformers to Dart 2 builders, we encountered several constraints that made us choose between dropping backwards compatibility _(mainly support for props class inheritance)_, and a less-than-optimal boilerplate.
To make the Dart 2 transition as smooth as possible, we chose to keep the new boilerplate version as backwards-compatible as possible, while compromising the cleanliness of the boilerplate. In time, we found that this wasn't great from a user experience or from a tooling perspective.
Knowing this, and having dropped …
=> CPLAT-11530: Migrate to new over_react boilerplate

.travis.yml, lib/src/over_react_test/jacket.dart
I noticed that the errors encountered in TestJacket when using function components could use just a touch more information to help guide users.
- Add note about using `Wrapper` component to enable `getByTestId`
- Add note about using `mountNode` directly if possible
- Update doc comments to match error messages
- Add more info around function components in TestJacket error messages and doc comments …
=> CPLAT-11842 Update instructions in TestJacket when using function components

.travis.yml, CHANGELOG.md, build.yaml, lib/src/over_react_test/common_component_util.dart, lib/src/over_react_test/test_helpers.dart, pubspec.yaml, test/over_react_test/common_component_util_test.dart, test/over_react_test/utils/test_common_component_new_boilerplate.dart
This release addresses:
* Fix prop forwarding tests false positives
Tests that had `commonComponentTests.getUnconsumedPropKeys()` returning a list of
keys that included keys within mixins that were actually being consumed by the component
were not failing as expected.
e.g. this situation should have resulted in test failures, but it did not:
Component's consumedProps:
```dart
@override
get consumedProps => propsMeta.forMixins({
SomePropsMixin,
});
```
Component's commonComponentTests:
```dart  
group('common component tests', () {
commonComponentTests(ComponentFactory, getUnconsumedProps: (propsMeta) => [
...propsMeta.forMixin(SomePropsMixin).keys,
]);
});
```
=> CPLAT-12003 RM-76349 Release over_react_test 2.9.6 (Fix prop forwarding test false positives)

pubspec.yaml
Because OverReact and over_react_test rely on each other, OverReact 4.0.0 cannot resolve its dependencies unless over_react_test can resolve with OverReact 4.0.0.
Widen the acceptable over_react version range.
=> Widen OverReact constraint in preparation for v4.0.0

lib/src/over_react_test/wrapper_component.dart, pubspec.yaml, test/over_react_test/helper_components/sample_component.dart, test/over_react_test/helper_components/sample_component2.dart, test/over_react_test/jacket_test.dart, test/over_react_test/react_util_test.dart, test/over_react_test/utils/nested_component.dart, test/over_react_test/utils/test_common_component_new_boilerplate.dart, test/over_react_test/utils/test_common_component_required_props_commponent2.dart
In order to enable Workiva to transition to Dart >=2.9.0 with ease, a slight update to OverReact factory syntax
is required.
__Important:__
1. Remember to update your snippets in order to prevent accidental regressions in boilerplate. [Here](https://github.com/Workiva/over_react/blob/master/snippets/README.md)
is the reference for OverReact snippets.
1. To prevent incompatible boilerplate from being introduced, a react-boilerplate core-check has been activated. This
core check will fail if the incompatible mixin based boilerplate is introduced again to a project that has migrated already.
> For more information on why this migration is important, see [this wiki update](https://wiki.atl.workiva.net/pages/viewpage.action?pageId=182026853).
__NOTE:__ Only the mixin based boilerplate …
=> Update OverReact syntax to support Dart 2.9+

pubspec.yaml
* [Add changelog entry for 2.10.2](https://github.com/Workiva/over_react_test/pull/110)
* [Update OverReact syntax to support Dart 2.9+](https://github.com/Workiva/over_react_test/pull/111)
* [Update query(All)ByTestId to support searching in ShadowRoots](https://github.com/Workiva/over_react_test/pull/114)
Requested by: @kealjones-wk
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/over_react_test/compare/2.10.2...Workiva:release_over_react_test_2.11.0
Diff Between Last Tag and New Tag: https://github.com/Workiva/over_react_test/compare/2.10.2...2.11.0
This pull request can …
=> RM-89967 Release over_react_test 2.11.0

CHANGELOG.md
=> add 2.11.0 changelog

.github/workflows/dart_ci.yml, Dockerfile, pubspec.yaml
As a part of the Dart 2.13 transition, FROM google/dart:2.7 needs to be changed over to FROM google/dart:2.13.
=> Vanilla Dart images Need Updateing

.github/workflows/dart_ci.yml, pubspec.yaml
This updates the minimum Dart version that can be used to at least 2.11.0. Why 2.11.0 and not 2.13.4? Because setting it to 2.12.0 or higher opts the project into null safety (https://dart.dev/null-safety) which our code has not been migrated to yet. 
Once a project has been migrated to null safety it is ok to update the  minimum to 2.12.0 or even 2.13.4 since everyone at Workiva should be  using 2.13.4 now.
If CI passes please review and merge. Most Dart CI has already been updated to run under 2.13.4 already so updating the minimum here doesn't change any code, or CI circumstances.
If CI fails, it's likely because an image in the Dockerfile or skynet.yaml is still running an older version of Dart. It should be updated to one with Dart 2.13. A list of existing 2.13 images lives here …
=> Raise the Dart SDK minimum to at least 2.11.0

.github/workflows/dart_ci.yml, pubspec.yaml
Summary
---
Client Platform is updating dependencies! Read more details at
https://wiki.atl.workiva.net/display/CP/Dependency+Upgrades
This batch is to find and open PRs to upgrade dependency_validator to v2.
Additional manual work that might be needed (CP will do):
[ ] Run dependency_validator to repos that aren't running it,
but do have the dependency. 
[ ] Fix CI due to removing an ignore that was actually needed.
For more info, reach out to `#support-client-plat` on Slack.
[_Created by Sourcegraph batch change `Workiva/update_dep_validator`._](https://sourcegraph.wk-dev.wdesk.org/organizations/Workiva/batch-changes/update_dep_validator)
=> Upgrade dependency_validator

skynet.yaml
This PR adds a basic skynet.yaml. This repo has silently stopped being able to release since the passing skynet result was enforced in order to release. This unblocks being able to release and publishing a dart package.
For more info, reach out to `#support-frontend-architecture` on Slack.
=> Add basic skynet.yaml

CHANGELOG.md, pubspec.yaml
* [Raise analyzer minimum & unpin meta](https://github.com/Workiva/over_react_test/pull/140)
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/over_react_test/compare/2.11.4...Workiva:release_over_react_test_2.11.5
Diff Between Last Tag and New Tag: https://github.com/Workiva/over_react_test/compare/2.11.4...2.11.5
This pull request can be recreated by clicking [here](https://w-rmconsole.appspot.com/api/v2/rosie/reTriggerReleaseEvents/4871683861643264/?repo_name=Workiva%2Fover_react_test&pull_number=141)
=> RM-163394 Release over_react_test 2.11.5

pubspec.yaml
Summary
---
This is a batch change to apply a dependency range pin to the meta package
in order to avoid a "bad release". That version causes nearly all of our builds to
fail (anything on analyzer < 5).
So restricting the version range to <1.10.0 works around the issue until we
can upgrade to analyzer 5.
For more info, visit `#lang-dart` in Slack.
[_Created by Sourcegraph batch change `Workiva/avoid_meta_1_10_0`._](https://sourcegraph.plat.workiva.net/organizations/Workiva/batch-changes/avoid_meta_1_10_0)
=> Avoid meta 1.10.0

.github/workflows/dart_ci.yml, Dockerfile, pubspec.yaml
In order to make the upgrade to analyzer 5 more predictable,
Frontend Frameworks is adding a dev dependency on a new package
`workiva_dependency_constrainer` which constrains analyzer to ^2,
mockito to `'>=5.0.0 <5.3.0'` and meta to `'>=1.6.0 <1.10.0'`
Once analyzer 5 ready packages for over_react, dart_storybook,
puppeteer_platform, and json_serializable_3_5_2 are released
and tested, then a newer version of the constrainer will be
released to unpin analyzer and mockito. This will prevent
repos from upgrading in an unpredictable order or time and
keeps things how they are until we're all ready to upgrade at
the same time.
As part of this batch, the pin on mockito and meta in this repo
will be removed, since they are now handled by the constrainer.
The extra dependency validator ignores …
=> Add workiva_dependency_constrainer

pubspec.yaml
This batch will raise the minimum of workiva_dependency_constrainer
to one that requires analyzer 5, thus ensuring that a repo resolves
to analyzer 5. It also raises the minimums of other packages that
are needed, like built_value.
1. Probably the most common thing is that built_value generated code
will need to be regenerated. There should be no breaking changes in
this new generated code. Some repos have a make target called `gen`,
`gen-built` or similar, or just run a full `dart run build_runner build`
2. The temporary fix for Dart coverage needs to be removed. The fix
is to simply remove lines like these below from Github Actions. This PR
will have raised the minimum of the test package to 1.21.1 which is
the first version needed that removes the need to backpatched test
versions.
``` …
```
=> Rollout Analyzer 5

CHANGELOG.md, lib/src/over_react_test/js_component.dart
react-dart 7.0.0 will remove some APIs, including `React.createFactory` which is used in this package.
Let's address this usage ahead of time to enable easier consumer testing of that major. 
- Remove usage of deprecated `React.createFactory`.
- Update changelog so that it's ready to go when we trigger a release after merging this PR
- CI passes
[contributing-manual-testing]: https://github.com/Workiva/over_react_test/blob/master/CONTRIBUTING.md#ma …
=> FED-1852 Remove usages of deprecated APIs to be removed in react-dart 7.0.0

dart_test.yaml, lib/src/over_react_test/react_util.dart, test/over_react_test/react_util_test.dart, test/over_react_test_unsound/react_util_test.dart, test/unsound_test.dart, test/unsound_test.html
Consumers don't get a very helpful error when passing null into `queryByTestId` or `queryAllByTestId`.
Also, passing null into these methods always threw in v2 and will always throws in v3, so we could also make the args non-nullable.
- Make `root` argument to `queryByTestId`/`queryAllByTestId` non-nullable
- Improve errors when things are null
- Add tests
Behavior before this PR:
| | null-safe consumer | non-null-safe consumer |
| --- | --- | --- |
| `root` is `null` | Unhelpful "Unhandled node" Exception | Unhelpful "Unhandled node" Exception |
| `root` is non-null, `findDomNode(root)` is `null` | Unhelpful "Unhandled node" Exception | Unhelpful "Unhandled node" Exception |
Behavior after this PR:
| | null-safe consumer | non-null-safe consumer |
| --- | --- | --- |
| `root` is `null` | …
=> FED-2223 query(All)ByTestId null arg improvements

lib/src/over_react_test/common_component_util.dart, test/over_react_test/common_component_util_test.dart, test/over_react_test/utils/test_common_component_required_props.dart, test/over_react_test/utils/test_common_component_required_props_commponent2.dart
We need to also skip checking for warnings when required props are late. These are already verified through build/call in over_react
see motivation
=> FED-2285 Skip testing late nullable props in common component test utils

CHANGELOG.md, lib/src/over_react_test/react_util.dart, test/over_react_test/react_util_test.dart
Having the root arg to `query(All)ByTestId` [be non-nullable](https://github.com/Workiva/over_react_test/pull/157) is inconvenient for consumers who have implicit casts enabled and pass `dynamic` component instances into those functions.
Since any null errors would only occur in tests, we think it's worth going back to making them nullable just to save consumers effort when migrating to null safety.
- Make root args to `query(All)ByTestId` nullable
- Add null-safe test cases to ensure null can be passed statically, and throws as expected
- Update changelog
- CI passes
While we perform many automated checks before auto-merging, some manual checks …
=> FED-2451 Make root args to query(All)ByTestId nullable

.github/workflows/dart_ci.yml, CHANGELOG.md, dart_test.yaml, lib/src/over_react_test/common_component_util.dart, lib/src/over_react_test/console_log_utils.dart, lib/src/over_react_test/custom_matchers.dart, lib/src/over_react_test/dom_util.dart, lib/src/over_react_test/jacket.dart, lib/src/over_react_test/props_meta.dart, lib/src/over_react_test/react_util.dart, lib/src/over_react_test/validation_util.dart, lib/src/over_react_test/zone_util.dart, pubspec.yaml, test/over_react_test/common_component_util_test.dart, test/over_react_test/console_log_utils_test.dart, test/over_react_test/custom_matchers_test.dart, test/over_react_test/dom_util_test.dart, test/over_react_test/helper_components/sample_component.dart, test/over_react_test/helper_components/sample_component2.dart, test/over_react_test/jacket_test.dart, test/over_react_test/react_util_test.dart, test/over_react_test/utils/shadow_nested_component.dart, test/over_react_test/utils/test_common_component.dart, test/over_react_test/utils/test_common_component_new_boilerplate.dart, test/over_react_test/utils/test_common_component_required_props.dart, test/over_react_test/utils/test_common_component_required_props_commponent2.dart, test/over_react_test/validation_util_test.dart, test/over_react_test_unsound/react_util_test.dart, test/unsound_test.dart, test/unsound_test.html
As a first step to releasing version 3.0.0 of this library, we need to: 
1. Update the changelog to include information about the 3.0.0 release.
2. Merge the changes from the `v3_wip` branch into master without actually tagging it as a release.
Then, once [`over_react` version 5](https://github.com/Workiva/over_react/pull/898) has been released, we can consume it and release version 3 of this library while bumping the minimum `over_react` version at the same time.
=> FED-2442 Merge version 3.0.0 changes to master

.github/workflows/dart_ci.yml, pubspec.yaml
For Dart packages that have migrated to null safety (full or partial)
we can raise the minimum Dart SDK version to 2.19.0 instead of 2.12.0.
This will allow us to take advantage of new language features as soon as
files are migrated to null safety. We've shown that unmigrated consumers
do not have issues consuming packages with a higher minimum Dart SDK version.
- Raise minimum Dart SDK version to 2.19.0
[_Created by Sourcegraph batch change `Workiva/raise_min_dart_sdk_2_19`._](https://workiva.sourcegraphcloud.com/organizations/Workiva/batch-changes/raise_min_dart_sdk_2_19)
=> raise_min_dart_sdk_2_19

lib/src/over_react_test/common_component_util.dart, lib/src/over_react_test/console_log_utils.dart, pubspec.yaml
In preparation for React 18, suppress react_dom.render warnings like in https://github.com/Workiva/react-dart/pull/413 - this is the only thing needed to get tests passing in over_react_test on React 18
=> FED-3275 React 18 Prep

CHANGELOG.md, pubspec.yaml
* [FED-3275 React 18 Prep](https://github.com/Workiva/over_react_test/pull/170)
Requested by: @sydneyjodon-wk
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/over_react_test/compare/3.0.1...Workiva:release_over_react_test_3.0.2
Diff Between Last Tag and New Tag: https://github.com/Workiva/over_react_test/compare/3.0.1...3.0.2
This pull request can be recreated by clicking [here](https://w-rmconsole.appspot.com/api/v2/rosie/reTriggerReleaseEvents/4871683861643264/?repo_name=Workiva%2Fover_react_test&pull_number=171)
=> RM-302415 Release over_react_test 3.0.2

CHANGELOG.md, pubspec.yaml
* [no_entrypoint_imports](https://github.com/Workiva/over_react_test/pull/173)
* [FED-4062 Set up gha-dart-oss](https://github.com/Workiva/over_react_test/pull/174)
Requested by: @sydneyjodon-wk
Diff Between Last Tag and Proposed Release: https://github.com/Workiva/over_react_test/compare/3.0.2...Workiva:release_over_react_test_3.0.3
Diff Between Last Tag and New Tag: https://github.com/Workiva/over_react_test/compare/3.0.2...3.0.3
This pull request can be recreated by clicking [here](https://w-rmconsole.appspot.com/api/v2/rosie/reTriggerReleaseEvents/4871683861643264/?repo_name=Workiva%2Fover_rea …
=> RM-331659 Release over_react_test 3.0.3
